[package]
authors = ["C J Silverio <ceejceej@gmail.com>"]
edition = "2018"
name = "LOUDCRAB"
version = "0.2.3"

[dependencies]
anyhow = "1"
dotenv = "0.15.0"
log = "0.4.14"
markov = "1.1.0"
rand = "0.7.3"
redis = "0.17.0"
regex = "1"
simple_logger = "1"
slack = "0.23.0"
