[package]
authors = ["C J Silverio <ceejceej@gmail.com>"]
edition = "2018"
name = "LOUDCRAB"
version = "0.3.0"
[dependencies]
anyhow = "1"
dotenv = "0.15.0"
log = "*"
markov = "*"
rand = "0.7.3"
redis = "0.17.0"
regex = "1"
simple_logger = "1"
slack_api = { version = "0.23.1", features = [ "sync", "reqwest_blocking" ] }
