[package]
authors = ["C J Silverio <ceejceej@gmail.com>"]
default-run = "LOUDBOT"
edition = "2018"
name = "LOUDCRAB"
version = "0.3.0"

[dependencies]
anyhow = "1"
dotenv = "0.15.0"
log = "*"
markov = "*"
rand = "0.7.3"
redis = "0.17.0"
regex = "1"
serde = "*"
serde_json = "*"
simple_logger = "1"
smol = "*"
tide = "*"

[dependencies.slack_api]
features = ["sync", "reqwest_blocking"]
version = "0.23.1"
